### ISSUE TITLE
gwas.pvalue

### ISSUE THREAD

**Issue by Tigeeeeer** [BGI-shenzhen/LDBlockShow#12]
Hi,

Thanks for this amazing and convenient tool,

I would like to ask one questions:

why the y axis label is -lg(Pvalue) rather than -log(Pvalue)?
![out](https://user-images.githubusercontent.com/87870226/126811671-22c1fba6-1b63-488b-ab00-0dda4025813c.png)

Appreciate your help in advance!

**Comment by Tigeeeeer** [comment]
>

**Comment by hewm2008** [comment]
Dear @Tigeeeeer 
A  .   the Y axis  [-lg(Pvalue)] is the same with   [-log(Pvalue)  ], some one ask me to default is to lg ,also you can use this   
`perl   LDBlockShow-1.40/bin/ShowLDSVG      -InYName   "-log(Pvalue)"      ...
`

B  the file [ gwas.pvalue ] is the result of others tools ,  most gaws software  used  the diploid  calculation.

C  For whole chromosome  LDheatmap  ?
    The maximum number of SNPs recommended by the software is about 10,000. It is recommended to pick out  5k-1w  SNPs of the whole chromosome  genome according to sliding windows.
also set this Para [-NoShowLDist] at the chr length.
