### ISSUE TITLE
Increase the resolution

### ISSUE THREAD

**Issue by huw143** [BGI-shenzhen/LDBlockShow#13]
Dear friends,

Do you know how to increase the quality (resolution) of this output image?

Thank you very much,

Hu

**Comment by hewm2008** [comment]
Dear @huw143 
A:
     A.1   For small SNP sets, you can directly use the svg file.
     A.2   For large SNP sets, the default png resolution should be sufficient, but you can use **LDBlockShow-1.40/bin/ShowLDSVG -ResizeH 4096**   to modify the resolution.
B: also you can used the convert to  modify the resolution,like as 
    **convert -resize 4096 xxx.svg xxx.png**
