### ISSUE TITLE
multithread option?

### ISSUE THREAD

**Issue by wbsimey** [BGI-shenzhen/LDBlockShow#15]
Hello,
I have a large vcf (27 chromosomes (2.5Gb), 96 diploid samples, and >18 million SNPs) and I have done a fair amount of pre-filtering. I am testing LDBlockShow on our smallest chromosome (18Mb and >500,000 SNPs). 

I ran:

`LDBlockShow -InVCF Chr26_2pops_HW.vcf.gz -OutPut out  -Region Chr26_nm_RagTag:1:18055847 -OutPng -SeleVar 2`

I am getting the following warning and no command line prompt after 3 hours.
```
#Warning skip non bi-allelic(Singleton/ThreeMulti allelic) site, and total skip allelic sites number is :28792
#Warning skip high missing site, and total skip allelic sites number is :43138
#Warning skip low Minor Allele Frequency site, and total skip allelic sites number is :212107
##Start Region Cal...    :Chr26_nm_RagTag 1 18055847; In This Region TotalSNP Number is 239684
Warning: LDBlocks Region SNP Number too much, you may use the small region or more stringent conditions to filter the SNP
```
I can see from running 'top' that LDBlockShow is running and only using a single thread. I have two questions:
1. Should the process abort on these warnings? or is it going to complete its run and provide output files?
2. Is there a way to use multiple threads? I have 256 threads and 2 TB RAM.

**Comment by hewm2008** [comment]
Dear @wbsimey 

  1   The program does not recommend using more than **10,000** SNP sites, so if you run the entire chr, you need to set the number of SNPs. It is recommended to randomly select a site every 100kb.    I have already mentioned the procedure of randomly picking sites [here](https://github.com/BGI-shenzhen/LDBlockShow/issues/4)    

- [ ] https://github.com/BGI-shenzhen/LDBlockShow/issues/4

 2  [**Convert**]  just reminds you that this command is not installed in the system. When converting svg to png, use this **Convert** first, if not, it will call **svg2xxx.pl**  .It is recommended that you install the convert command first。

For Big SVG file  ---- > png
1) [convert](https://linux.die.net/man/1/convert) command is recommended to be pre-installed, although it is not required. 
  If your system does not have a **convert** command, svg2xxx.pl will be called. you can use the follow command to pre-install the  **convert**  command;
    `  sudo apt-get install ImageMagick`   or ` sudo yum  install  ImageMagick`



 3 The figure you drew is an incomplete inverted triangle, which has already reminded you : 
      _Tip: The region you inputed is greater than the Para [-NoShowLDist], and this will call LDheatmap to be  a not-complete triangle. You can modify the parameter [-NoShowLDist] according to your needs._
     so you just to replot the figure  by add para          **-NoShowLDist    chrlengthNumber**
    _./LDBlockShow-1.40/bin/ShowLDSVG    -InPreFix  Result.Frefix    -NoShowLDist    XXXX  -OutPut   LDheatmap_

**Comment by wbsimey** [comment]
Very helpful, thank you.
