### ISSUE TITLE
-NoLogP not working

### ISSUE THREAD

**Issue by huw143** [BGI-shenzhen/LDBlockShow#16]
Hello,

Could you help me solve the "-NoLogP" code by any chance?  it looks not working.

for example,

../bin/LDBlockShow -InVCF GWAS_Only_Chromosome_Biallelic.Filter_out.0.05MAF_50%Missing.vcf.gz -MAF 0.05 -Miss 0.6 -OutPut Chr2.4_58225679 -Region chr2.4:54758224-59306183 -SpeSNPName Chr2.4_58225679_spe.snp -InGWAS Chr2.4_58225679_gwas.pvalue -Cutline 5 -OutPng -SeleVar 1 -ShowNum -BlockType 3 -BlockCut 0.8 -NoLogP

 I was trying to put -NoLogP at different positions, it still did not work.

Any help would be appreciated!

Hu

**Comment by hewm2008** [comment]
@huw143  
-NoLogP  is the Para for the replot bin  [**ShowLDSVG**] ,no the  **LDBlockShow** .  ,after LDBlockShow , you can replot by follow :

`
LDBlockShow-1.40/bin/ShowLDSVG    -InPreFix   Chr2.4_58225679    -SpeSNPName Chr2.4_58225679_spe.snp -InGWAS Chr2.4_58225679_gwas.pvalue -Cutline 5 -OutPng  -ShowNum   -BlockCut 0.8 -NoLogP   
`
