### ISSUE TITLE
.vcf file has a GT half-call.

### ISSUE THREAD

**Issue by PengJia6** [BGI-shenzhen/LDBlockShow#17]
Hi,

I used LDBlockShow to analysis my vcf file. But I got the following error.

`Error: Line 5230 of .vcf file has a GT half-call.     `    
`Use --vcf-half-call to specify how these should be processed
`

but I did not find --vcf-half-call option in this command.

BTW, the version of the LDBlockShow I used is  **1.40**. I have 74915 phased SNV from 32 samples. 

My command is as follows

`LDBlockShow -InVCF final.snv.alt.vcf.gz -OutPut ./this_snv_LD -Region chr10:65726063-73410226`

Thanks!

**Comment by hewm2008** [comment]
Dear @PengJia6 
I think some format of VCF file.

if your vcf format is haploid vcf format, I suggest to make some changes. haploid ---》 Diploid
you should change the GT
"0" ---> "0|0" or "0/0"
"1" ---> "1|1" or "1/1"
In theory, the data of the haploid ---> diploid VCF data, which does not affect the change of Decay.
https://github.com/BGI-shenzhen/PopLDdecay/issues/7

also you can send me your data to my email, I try to run this for you.

**Comment by PengJia6** [comment]
Thanks for your response! 

My sample is diploid, I removed the record with missed GT, such as "./." or "./1",  and it worked. 

Thanks again!
Peng

**Comment by hewm2008** [comment]
Thanks for using the software.
best wishes
