### ISSUE TITLE
clarify snp comparisons in triangle

### ISSUE THREAD

**Issue by Apis-DeLorian** [BGI-shenzhen/LDBlockShow#18]
I was just wanting to clarify how the r^2 values in the triangle output correspond to specific pairs of snps. Is the first row and first column element the r^2 of the snps of the first and last positions? The first column and last row element is the r^2 value corresponding to the first and second snp? The last column and first row element is the r^2 of the last and second to last snp?

Thanks

**Comment by hewm2008** [comment]
dear @Apis-DeLorian 
Here  I provide an example here，as follows: Hope this will make it easier for you to understand

[data Mat.xlsx](https://github.com/BGI-shenzhen/LDBlockShow/files/7551907/Mat.xlsx)

![image](https://user-images.githubusercontent.com/10345833/142138353-78aa53c7-34b2-4447-90a3-02474d226ed4.png)

**Comment by Apis-DeLorian** [comment]
@hewm2008  Thank you. Yes, this clarified everything for me!
