### ISSUE TITLE
Error: Multiple instances of '_' in sample ID

### ISSUE THREAD

**Issue by sandipmkale** [BGI-shenzhen/LDBlockShow#2]
Hello I am getting following error: but don't know how to specify --double-id 

Error: Multiple instances of '_' in sample ID.
If you do not want '_' to be treated as a FID/IID delimiter, use --double-id or
--const-fid to choose a different method of converting VCF sample IDs to PLINK
IDs, or --id-delim to change the FID/IID delimiter.

Please help

**Comment by hewm2008** [comment]
Dear @sandipmkale 
you can try to convert the  file form  by on the command line first.  such as  for  chr1:10000-20000   (bed+fam+bim)  
`LDBlockShow-1.36/bin/plink     --file inprefix   --export vcf  --out   outfix   --allow-extra-chr  --chr   chr  --from-bp   10000  --to-bp 20000       **--const-fid 0**   `  
or     [map+ped]
`LDBlockShow-1.36/bin/plink     --bfile inprefix   --export vcf  --out   outfix   --allow-extra-chr  --chr   chr  --from-bp   10000  --to-bp 20000       **--const-fid 0**      `  

then you will get the region vcf file    [outfix.vcf ] ,so you  can use this VCF file  to follow the [LDBlockshow]  
./LDBlockShow-1.36/bin/LDBlockShow   -InVCF   -Region  chr1:10000-20000  -OutPut  outPrefix   -OutPng      -othrPara
