### ISSUE TITLE
I used LDBlockShow to analysis my vcf file. But I can't get any output.

### ISSUE THREAD

**Issue by GuLinLin-JMU** [BGI-shenzhen/LDBlockShow#20]
Hi,

I used LDBlockShow to analysis my vcf file. But I can't get any output.

Start Time :
Tue Mar  1 16:37:37 CST 2022
#warning skip Indel site, there are total skip Indel sites number is : 1
#Warning skip low Minor Allele Frequency site, and total skip allelic sites number is :103
##Start Region Cal...	 :19 44889596 45932557; In This Region TotalSNP Number is 130
Start draw... SVG info: SNPNumber :130 , SVG (width,height) = (4485,4797)
In Big SNP Number :130 ,Para -NumGradien suggest be maxValue : 32 ,auto be it
Argument "" isn't numeric in log at /mnt/data9/gulinlin/biosoft/LDBlockShow-master/bin///ShowLDSVG line 992.
Can't take log of 0 at /mnt/data9/gulinlin/biosoft/LDBlockShow-master/bin///ShowLDSVG line 992.
	Tip: The region you inputed is greater than the Para [-NoShowLDist], and this will call LDheatmap to be  a not-complete triangle. You can modify the parameter [-NoShowLDist] according to your needs.
find blocks...
Start draw... SVG info: SNPNumber :130 , SVG (width,height) = (4485,4797)
Argument "" isn't numeric in log at /mnt/data9/gulinlin/biosoft/LDBlockShow-master/bin//ShowLDSVG line 992.
Can't take log of 0 at /mnt/data9/gulinlin/biosoft/LDBlockShow-master/bin//ShowLDSVG line 992.
End Time :
Tue Mar  1 16:39:26 CST 2022

My command is as follows
$LDBlockShow_dir/LDBlockShow -InPlink sample -OutPut ./Lipoprotein_A_imputed/Lipoprotein_A_imputed_chr19 -Region 19:44889596:45932557 -InGWAS Lipoprotein_A_imputed.pvalue -SeleVar 2 -OutPng  
$LDBlockShow_dir/ShowLDSVG -InPreFix ./Lipoprotein_A_imputed/Lipoprotein_A_imputed_chr19  -OutPut out_chr19 -InGWAS Lipoprotein_A_imputed.pvalue -NoShowLDist 20000000 -Cutline 6.913226 -PointSize 1 -NumGradien 32 -OutPng
Thanks!

**Comment by hewm2008** [comment]
the chr name of gwas file  and vcf file  should be the same . please check it  .
The input chr name should be the same with the VCF files . also the chr name of gwas file should be the same .

**Comment by GuLinLin-JMU** [comment]
Thanks for your response! I have a new problem.
Start Time :
Fri Mar  4 11:13:22 CST 2022
#warning skip Indel site, there are total skip Indel sites number is : 2
#Warning skip low Minor Allele Frequency site, and total skip allelic sites number is :324
##Start Region Cal...    :2 232482038 236228699; In This Region TotalSNP Number is 469
find blocks...
In Big SNP Number :469 ,Para -NumGradien suggest be maxValue : 32 ,auto be it
Start draw... SVG info: SNPNumber :469 , SVG (width,height) = (5393.5,5768.7)
        Tip: The region you inputed is greater than the Para [-NoShowLDist], and this will call LDheatmap to be  a not-complete triangle. You can modify the parameter [-NoShowLDist] according to your needs.
Can't take log of 0 at /mnt/data9/gulinlin/biosoft/LDBlockShow-master/bin///ShowLDSVG line 989.
In Big SNP Number :469 ,Para -NumGradien suggest be maxValue : 32 ,auto be it
Start draw... SVG info: SNPNumber :469 , SVG (width,height) = (5393.5,5768.7)
Can't take log of 0 at /mnt/data9/gulinlin/biosoft/LDBlockShow-master/bin//ShowLDSVG line 989.
End Time :
Fri Mar  4 11:22:25 CST 2022
Thanks!

**Comment by hewm2008** [comment]
code line  989  is :
$hashPvalue{$key}=0-((log($hashPvalue{$key}))/log(10));

so I thinks in this region(:2 232482038 236228699) the may some gwas pvalue be exists 0 , you can awk this region gwas.pvalue. and check it  at   your  GwasPvalue.file 
A:
you can awk this region gwas.palvue. and check it
cat GwasPvalue.file | awk '$1 ==2 && $2 >=232482038 && $2< 236228699'

B ：

I think it may be the effect of the line end of different systems. you can execute the following command
dos2unix GwasPvalue.file
