### ISSUE TITLE
Dose this tool need phenotypes?

### ISSUE THREAD

**Issue by Alice-yyt** [BGI-shenzhen/LDBlockShow#21]
Hello every, I conduct the commend: LDBlockShow   -InVCF aln_sorted2.vcf   -OutPut  out   -Region  NC_001802.1:1:2000  -OutPng  -SeleVar 2 
and got the result: #Warning skip non bi-allelic(Singleton/ThreeMulti allelic) site, and total skip allelic sites number is :15
##Start Region Cal...	 :NC_001802.1 1 2000; In This Region TotalSNP Number is 207
find blocks...
Warning: Skipping --blocks, since there are less than two founders with
nonmissing phenotypes.  (--make-founders may come in handy here.)
mv: cannot stat ‘out.plink.blocks.det’: No such file or directory
gzip: out.blocks: No such file or directory
Can't locate SVG.pm in @INC

I don’t why I got this warnings. What information should we provide in the vcf file for LDBlockShow? 

Thank you

**Comment by hewm2008** [comment]
@Alice-yyt   
A:    the SVG.pm   :     I think it's because of your incomplete download.  you can redownload the  soft , Dir [bin/svg_kit]  must be exists .
B :     you can change the  blocks  method  by add para  [  -BlockType  2  ]    .  or see  more  at  :  https://www.biostars.org/p/205746/
