### ISSUE TITLE
Why it went wrong?

### ISSUE THREAD

**Issue by janking1** [BGI-shenzhen/LDBlockShow#22]
My code was shown below:   ./LDBlockShow  -InPlink 1557_indifreq_cal_pc1_more_equ_0_1557_indi -Region 4:72694947-7869226 -OutPut 1557_indifreq_cal_pc1_more_equ_0_1557_indi  -OutPdf ;But I come across the message like "Error: Invalid .bed file size (expected 3147663 bytes)".  I checked my data and I find the expected size was the same as my data, how can I  solve this problem? It would be great if I receive your reply soon.

**Comment by janking1** [comment]
sorry about that.I solve this problem already, turns out it came from the way I modified my sample ID

**Comment by hewm2008** [comment]
you region give wrong  :chr start end     no chr  end end  72694947  >  7869226    7869226* ?   
you can try:
  ./LDBlockShow -InPlink 1557_indifreq_cal_pc1_more_equ_0_1557_indi -Region 4:72694947-78692260   -OutPut 1557_indifreq_cal_pc1_more_equ_0_1557_indi -OutPdf       -OutPng

plink  -file   1557_indifreq_cal_pc1_more_equ_0_1557_indi      --allow-extra-chr    --export vcf --out    Region.vcf   --chr    4  --from-bp     72694947   --to-bp   78692260

**Comment by janking1** [comment]
thanks,that work!



At 2022-04-18 18:00:46, "hewm2008" ***@***.***> wrote:

you region give wrong :chr start end no chr end end 72694947 > 7869226 7869226* ?
you can try:
./LDBlockShow -InPlink 1557_indifreq_cal_pc1_more_equ_0_1557_indi -Region 4:72694947-78692260 -OutPut 1557_indifreq_cal_pc1_more_equ_0_1557_indi -OutPdf -OutPng

plink -file 1557_indifreq_cal_pc1_more_equ_0_1557_indi --allow-extra-chr --export vcf --out Region.vcf --chr 4 --from-bp 72694947 --to-bp 78692260
