### ISSUE TITLE
`ZLIB_1.2.9' not found

### ISSUE THREAD

**Issue by janking1** [BGI-shenzhen/LDBlockShow#23]
Here is my error,it seems that this error comes from  converting SVG 2 PNG, I have already install the "zlib 1.2.9" and using command  "export LIBRARY_PATH=$LIBRARY_PATH:/WORK/scau_ljq_1/USER/szq/2022.4.15dsq_LD_haploview/lib" to set the path to "zlib 1.2.9", but it didn't work and shows the same error, I wonder is there somewhere I can truly set the path to "zlib 1.2.9":
> system(paste0("./LDBlockShow ",
+               " -InPlink sub_snp_PLAG1_sub_eigen_expand_sig_3Mb_bonferroni_0.01_200k_1557_indi ",
+               " -Region 4:72694947:78692263 ",
+               " -OutPut ","sub_snp_PLAG1_sub_eigen_expand_sig_3Mb_bonferroni_0.01_200k_1557_indi ",
+               " -OutPng "
+               ))
#Warning skip low Minor Allele Frequency site, and total skip allelic sites number is :10303
##Start Region Cal...	 :4 72694947 78692263; In This Region TotalSNP Number is 7184
Start draw... SVG info: SNPNumber :7184 , SVG (width,height) = (6609.28,4885.12)
Too  many SNP site 7184 , I suggest that you randomly select fewer sites to reshow , and here I try to draw ...
In Big SNP Number :7184 ,Para -NumGradien suggest be maxValue : 10 ,auto be it
	Tip: The region you inputed is greater than the Para [-NoShowLDist], and this will call LDheatmap to be  a not-complete triangle. You can modify the parameter [-NoShowLDist] according to your needs.
convert   SVG ---> PNG ...
/usr/bin/convert: /WORK/app/anaconda3/5.3.0/lib/./libuuid.so.1: no version information available (required by /usr/lib64/libSM.so.6)
/usr/bin/convert: /WORK/app/zlib/1.2.8/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /WORK/app/anaconda3/5.3.0/lib/./libpng16.so.16)
ALL done
find blocks...

**Comment by hewm2008** [comment]
Hi  @janking1 
you can manually convert the svg to png to see if this error is reported.
`convert  xxx.svg  xxx.png `

If it reports a considerable error, it is a problem with the installation of your command convert, you can reinstall this command first.

你好   你手动将svg转png看看是否报这个错，若报相当的错，当是你的命令convert安装的问题，你可以重新安装一下这个命令看看
`convert  xxx.svg  xxx.png `

**Comment by janking1** [comment]
Thanks for help, it work. It seems that it is a problem with the installation of my command convert,  may I ask if there would be trouble if I convert SVG directly without using ShowLDSVG?

**Comment by hewm2008** [comment]
No problem, you can manually convert svg to png format by other methods/software.
