### ISSUE TITLE
How can I close the quality check on my data?

### ISSUE THREAD

**Issue by janking1** [BGI-shenzhen/LDBlockShow#25]
Hi there, I have two genotype data in PLINK format with the same BIM file and different FAM file, now I tried to compare the LD in two dataset without quality check, how can I do that in LDBlockShow?

**Comment by hewm2008** [comment]
you can run LDblockShow with these two datas separately, you will get two graphs, then you can compare the difference between the two graphs

**Comment by janking1** [comment]
> you can run LDblockShow with these two datas separately, you will get two graphs, then you can compare the difference between the two graphs

Maybe my question wasn't described clear enough. My problem is I did draw two graphs separately, but these two graphs didn't have the same start bp and end bp because of the auto data check in LDblockShow and now I want to close it so I can draw two graphs without quality check and compare them in the same  total SNP .

**Comment by hewm2008** [comment]
Indel and  no bi-allelic SNP will must be filter,only  bi-allelic SNP will be take in .
The  other  filter para（maf miss hete ）,  you can set it to be a  extreme values ​​make it unfiltered. 
I  suggest you can try
<pre>
   LDBlockShow-1.40/bin/LDBlockShow   -MAF    0.0001   -Miss    1.0   -HWE    0  -Het   1.0  ...
 </pre>

		-MAF           <float>    Min minor allele frequency filter [0.05]
		-Miss          <float>    Max ratio of miss allele filter [0.25]
		-HWE           <float>    Exact test of Hardy-Weinberg Equilibrium for SNP Pvalue[0]
		-Het           <float>    Max ratio of het allele filter [1.00]
