### ISSUE TITLE
Error: Line 28 of .vcf file has a GT half-call.

### ISSUE THREAD

**Issue by Sour01** [BGI-shenzhen/LDBlockShow#26]
Hi!
I use Plink to convert the my vcf format，but I encountered the following problems:

Error: Line 28 of .vcf file has a GT half-call.
Use --vcf-half-call to specify how these should be processed.

But I didn't find  --vcf-half-call.

Error: Missing --vcf-half-call parameter.
For more information, try "plink --help <flag name>" or "plink --help | more".

My command is :
  plink --vcf PT8.vcf --recode HV --out pap.region.hv --allow-extra-chr

Thanks!

**Comment by hewm2008** [comment]
you can see this at this  [issues 17](https://github.com/BGI-shenzhen/LDBlockShow/issues/17)
