### ISSUE TITLE
BEGIN failed--compilation aborted at /bin/ShowLDSVG line 24.

### ISSUE THREAD

**Issue by icc317** [BGI-shenzhen/LDBlockShow#29]
I use conda install -c bioconda ldblockshow ,but ShowLDSVG is not working,so can you help me ?
BEGIN failed--compilation aborted at /bin/ShowLDSVG line 24.

**Comment by hewm2008** [comment]
ShowLDSVG is a pure perl script and does not need to be compiled, so please make sure your system has **perl** and installed the **perl-svg** package

**Comment by icc317** [comment]
>conda install -c bioconda perl-svg
I use this command to insatll, that show # All requested packages already installed.Therefore I use MethodB to insatll, when I run  make, that show error: 'timespec_get' has not been declared in '::',
make[1]: *** [Makefile:297: LDBlockShow.o] Error 1
make[1]: Leaving directory '/software/LDblock/LDBlockShow'
make: *** [Makefile:178: all] Error 2

**Comment by icc317** [comment]
> Methold A : ShowLDSVG is a pure perl script and does not need to be compiled, so please make sure your system has **perl** and installed the **perl-svg** package
> 
> please install the **SVG module** from this URL [ https://metacpan.org/release/SVG ]
> 
> Methold B : Users can install it with the following ： git clone https://github.com/hewm2008/LDBlockShow.git cd LDBlockShow ; chmod 755 configure ; ./configure; make; mv LDBlockShow bin/; # [rm *.o]

**Comment by hewm2008** [comment]
cp  -r         /software/LDblock/LDBlockShow/bin/svg_kit            /bin/    ;  


then you can re-run the      /bin/ShowLDSVG

**Comment by icc317** [comment]
Because I'm not an administrator, when I use cp -r /software/LDblock/LDBlockShow/bin/svg_kit /bin/ ;cp: cannot create directory '/bin/svg_kit': Permission denied,  if there's any other way to solve it.

**Comment by hewm2008** [comment]
cp  -r     /bin/LDBlockShow    /software/LDblock/LDBlockShow/bin/   ; 
chmod 755 -R    /software/LDblock/LDBlockShow/bin/

then  rerun the    /software/LDblock/LDBlockShow/bin/ShowLDSVG

**Comment by icc317** [comment]
Thank you very much! I can run it. I also have a  question, Because  my region is large, so this will call LDheatmap to be  a not-complete triangle, therefore  can I  know the max Distance?

**Comment by icc317** [comment]
Thank you very much! I can run it!
