### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sheshen22** [BGI-shenzhen/LDBlockShow#31]
Hi, I used the sample file and a Segmentation fault occurred.  I'm using Ubuntu 20.04.5 LTS from WSL, and I don't know if you have a fix.  Thank you, sir. 
 ./LDBlockShow  -InVCF ../example/Example1/Test.vcf.gz -OutPut out -Region chr11:24000000:24400000 -OutPng -SeleVar 2

#Detected VCF File is phased file with '|', Read VCF in Phase mode
#Warning skip low Minor Allele Frequency site, and total skip allelic sites number is :11
##Start Region Cal...    :chr11 24000000 24400000; In This Region TotalSNP Number is 7
find blocks...
Segmentation fault
mv: cannot stat 'out.plink.blocks.det': No such file or directory
gzip: out.blocks: No such file or directory
Warining: SVG module in Perl is missing, trying to loading the built-in [SVG.pm]...
Loading SVG module done
Start draw... SVG info: SNPNumber :7 , SVG (width,height) = (455,385)
convert   SVG ---> PNG ...
ALL done

./LDBlockShow -InVCF ../Example1/Test.vcf.gz -OutPut out -Region chr11:24100000:24200000 -InGWAS ../Example2/gwas.pvalue  -SeleVar 2
Segmentation fault

**Comment by hewm2008** [comment]
应该是plink的软件没办法在你的 WSL上运行，这儿建议尽量用linux的;   
应急的方式加上    -BlockType      2 的参数，用另一种找ld blocks的method，当可以运行

**Comment by sheshen22** [comment]
> 应该是plink的软件没办法在你的 WSL上运行，这儿建议尽量用linux的; 应急的方式加上 -BlockType 2 的参数，用另一种找ld blocks的method，当可以运行

感谢您的回答与建议。我更换成虚拟机ubuntu之后可以正常运行了。

**Comment by sheshen22** [comment]
![image](https://user-images.githubusercontent.com/104003939/228118419-259c2d75-1445-4dfb-93e7-7bcdf319f41b.png)
您好，还有一个小问题，就是如何才能显示具体的位置，而不是以Mb为单位。谢谢您~
![image](https://user-images.githubusercontent.com/104003939/228118565-3b9b0f2d-2bc0-4b0a-8b20-1dd395440e0e.png)

**Comment by hewm2008** [comment]
bin/ShowLDSVG 里面的第       747行和 762行  你自己改一下再运行 
747行    my $Textbin=1000000; my $label="Mb";
和 
762行   $Textbin=1000000; $label="Mb"; 

改为
 my $Textbin=1 my $label="bp";
和 
 $Textbin=1; $label="bp";

**Comment by hewm2008** [comment]
感觉是m1的问题，要下m1下的plinks版本，若能单独运行plink出帮助文档说明下载对了版本。
建议还是在linux下运行为好

**Comment by Nananchenjpg** [comment]
请问我遇到了Segmentation fault (core dumped)命令是/pdata1/home/liepngzhong/softwares/LDBlockShow-master/bin/LDBlockShow -InVCF /pdata1/home/liepngzhong/ccc/tc2record/output/chr2_NBA.vcf -OutPut re5 -Region 2:2220000-2230000 -OutPng -SeleVar 1  这怎么办啊求求

**Comment by hewm2008** [comment]
你的输入文件  VCF中某一行格式有异常
