### ISSUE TITLE
请问如何才能显示正确的gene名称

### ISSUE THREAD

**Issue by sheshen22** [BGI-shenzhen/LDBlockShow#32]
示例文件中GFF格式如下：
![image](https://user-images.githubusercontent.com/104003939/228490930-b7300415-e5ca-434e-878a-90f6e422eddf.png)
但是按参考文档里面说的GFF3格式文档格式是：
![image](https://user-images.githubusercontent.com/104003939/228491675-f66383ef-73f4-4336-8a10-ac06d87c572a.png)
或者是
![image](https://user-images.githubusercontent.com/104003939/228493440-7672f55a-d0b3-416f-ad33-2713efb288e2.png)

因此，不能显示出正确的gene名称
请问如何才能解决？或者如示例的GFF格式应该去哪里下载?
谢谢您

**Comment by hewm2008** [comment]
把你的文件   最后一列  你只留下对应的 基因名就行了

**Comment by jihui-boop** [comment]
你好，要怎么留下对应的基因名称
