### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jcakon** [BGI-shenzhen/LDBlockShow#33]
When I use the example code " ../../bin/LDBlockShow -InVCF Test.vcf.gz -OutPut out1 -Region chr11:24100000:24200000 -OutPng -SeleVar 1 "
There is a error means"Can't find the [ convert ] bin in your $PATH, I try to convert svg by /home/weizian/LDBlockShow-1.40/bin/svg_kit/svg2xxx.pl "
What should I do to solve this problem.
Thank you!

**Comment by hewm2008** [comment]
For Big SVG file ---- > png

[convert](https://linux.die.net/man/1/convert) command is recommended to be pre-installed, although it is not required.
If your system does not have a convert command, svg2xxx.pl will be called. you can use the follow command to pre-install the convert command;
  sudo apt-get install ImageMagick or  sudo yum  install  ImageMagick
