### ISSUE TITLE
8547 segmentation fault

### ISSUE THREAD

**Issue by haduong136** [BGI-shenzhen/LDBlockShow#38]
Hi,

I tried to run the LDBlockShow but it ran into the "8547 segmentation fault" and I'm not sure how to fix it, could you please check? Thanks!

➜  Ara_test git:(main) ✗ ../../bin/LDBlockShow -InVCF Ara_Ch4.vcf -OutPut  out   -Region  chr4:920000:9240000  -OutPng
[1]    8547 segmentation fault  ../../bin/LDBlockShow -InVCF Ara_Ch4.vcf -OutPut out -Region  -OutPng

I attached here the head 50 of my vcf 
[50_Ara_Chr4.txt](https://github.com/BGI-shenzhen/LDBlockShow/files/14172126/50_Ara_Chr4.txt)

**Comment by hewm2008** [comment]
I have never encountered this error. I feel that there may be a problem with the SNP site format in your region. You can extract the SNP in this region and send it to me, and I will help you take a look.
