### ISSUE TITLE
Color options

### ISSUE THREAD

**Issue by elissaralam** [BGI-shenzhen/LDBlockShow#39]
Hello,

Thanks for developing LDblock show! I see the default colors for SNPs in the regional Manhattan plots are blue for insignificant SNPs and red for signifcant ones. Is it possible to change those colors? I don't see an option to do so in the manual but i've seen LDBlockShow-generated figures in manuscripts with different colors than the default.

Thanks a lot for any help with this,
Elissa

**Comment by hewm2008** [comment]
Hi, Elissa 
I don’t quite understand what you mean. I feel that adding a parameter "-TopSite" will change the relevant color, which may be what you want. You can try this parameter to see
