### ISSUE TITLE
gwas.pvalue format

### ISSUE THREAD

**Issue by huw143** [BGI-shenzhen/LDBlockShow#8]
Hi LDBlockShow group,

I raised another question that do you have an example of gwas.pvalue format? Thanks a lot,

Hu

**Comment by hewm2008** [comment]
Dear @huw143  
you can see it  at the   **example/Example3/gwas.pvalue**. 
also here : 
https://github.com/BGI-shenzhen/LDBlockShow/blob/master/example/Example3/gwas.pvalue
There are three columns :  [chr site  pvalue] 

By the way , If it is gwas, the software will log the data, so please make sure that your pvalue **cannot be 0**.  If it is 0, you can take a minimum value  for it .

**Comment by huw143** [comment]
Super thanks for your help @hewm2008

**Comment by hewm2008** [comment]
In the New ver of  the V1.40 after 2021-12-06,  the  gwas file format 
There are three columns : [chr site pvalue]
also can accept the new format(gwas.pvalue.**cvs**) here
There are three columns : [chr,site,pvalue]
