### ISSUE TITLE
SVG size can not be adjusted, I got a partial SVG

### ISSUE THREAD

**Issue by huw143** [BGI-shenzhen/LDBlockShow#9]
Hi He,

I found one question that the SVG size could not be adjusted by -ResizeH function, I used the command line in the attachment and got a partial plot (please see the bottom of the plot). Please check the attachment for details, thanks a lot for your continuous helps.

Best regards,

Hu
![size](https://user-images.githubusercontent.com/64991387/111195718-2cdf3380-8582-11eb-90dd-f0b960e7ba80.PNG)
![out](https://user-images.githubusercontent.com/64991387/111195909-5bf5a500-8582-11eb-9174-e783b6e9f7e5.png)

**Comment by hewm2008** [comment]
the program is designed like this: The **ResizeH** parameter is to limit the maximum possible height of the canvas.
so you  height=385   <  4096 , will take the  385 as the final height.

Other infomation:
A:  when the  SNP  small , The svg file size is small, you can edit it directly (as :Adobe Illustrator ).  Enlarge the picture proportionally
B：Convert it manually   by one of the following command ：
         B.1 : 
             **convert    -resize   4096  xxx.svg xxx.png**  
         B.2 
                **perl    LDBlockShow-*/bin/svg_kit/svg2xxx.pl   xxx.svg     -t png   --height**

**Comment by hewm2008** [comment]
@huw143  
you  can use the  para    **-adjHeatmap**   to make the  LDheatmap move up and down.   
-adjHeatmap      <f>   : The ratio[-0.250,0.25] to Up[-0.25,0] or Down[0,0.25] the HeatMap in canvas [0]
try to use this : 
    **perl ShowLDSVG -MoreHelp -0.1   ...   **

**Comment by huw143** [comment]
@hewm2008 Thanks a lot for your help, it solved by your helpful suggestions. 

Best regards,

Hu
